### PR TITLE
Add first 32 control chars

### LINKED ISSUE #98: Add non-printable ASCII control characters mapped to empty glyph
Related #95 #96 

Please add the full range of non-printable control character encodings (U+0000 to U+001F) mapped to a zero adv width, empty (no outline) glyph.  These glyphs should be available in the variable font and static font format builds in order to work around the font fallback tofu issue that Dave raised in #95.

### PR DESCRIPTION
**Pull request by m4rc1e**
As requested by the Android team. Supersedes #96, Fixes #98, #99

@chrissimpkins. Once the CI is done making the fonts, I'll post the link so the team can test.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Just like to point out that these characters are only getting added to the Android cut. They're being mapped to the first empty glyph in the font.

**Comment by m4rc1e** [comment]
@chrissimpkins here's a link to the generated fonts, https://github.com/googlefonts/roboto-classic/suites/7273375516/artifacts/292791016

**Comment by m4rc1e** [comment]
Here's a diffenator2 report (tool still wip)

[report.zip](https://github.com/googlefonts/roboto-classic/files/9071595/report.zip)

We can see that the cmap has been changes as expected.

Screenshot 2022-07-08 at 12 22 11

**Comment by chrissimpkins** [comment]
Thanks Marc! I will reach out to the team to discuss the next step.

**Comment by m4rc1e** [comment]
Thanks! I'll be away from today until the 20th of July so if the team is happy, you may need to find someone (or yourself) to cut a release. It's fairly straight forward, you can create a release using the github gui and just attach the fonts generated by the ci.

**Comment by chrissimpkins** [comment]
I reached out to Android team today to followup on this request.  We are waiting on confirmation that this addresses the issue.

**Comment by davelab6** [comment]
I believe the customer team accepted this, so can be merged

**Comment by m4rc1e** [comment]
Cool. I'll merge this and then add #97 and cut a new release.

**Comment by chrissimpkins** [comment]
Thanks Marc!

**Pull request merged**
