### PR TITLE
Fixing STAT problem

### LINKED ISSUE #91: Add a SemiBold entry in STAT (like in fvar)
See google/fonts#3267

### PR DESCRIPTION
**Pull request by aaronbell**
The `gen_stat.py` file mistakenly leaves out the SemiBold instance, causing Mac Word to improperly render the SemiBold instance as "Medium":

Screen Shot 2021-07-14 at 4 15 08 PM

This fix corrects that issue. 
Closes #91

### CODE REVIEW

**Comment by davelab6** [comment]
@m4rc1e before merging the other pr, please integrate this

**Comment by thlinard** [comment]
Still not merged for version 3.005.

**Comment by auduongtuan** [comment]
Any update on this?

**Comment by m4rc1e** [comment]
Closing fixed in #107

**Pull request closed without merging**
