### PR TITLE
*.ufo.features.fea: add sups and subs features

### LINKED ISSUE #97: Missing cmap entries for superscript, subscript digits
B/213345773 was reported internally that Roboto is Missing cmap entries for superscript, subscript digits

### PR DESCRIPTION
**Pull request by m4rc1e**
Fixes #97

@kpozin once the ci has finished genning the fonts, I'll pass a link over. I've had a quick look myself and they're working well.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Ok, the ci has finished. Font can be downloaded from https://github.com/googlefonts/roboto-classic/suites/7541190063/artifacts/311024320

Can confirm sub and sups features are now working:

```
hb-shape Roboto\[ital\,wdth\,wght\].ttf --features sups 0123456789
[zerosuperior=0+751|onesuperior=1+751|twosuperior=2+751|threesuperior=3+751|uni2074=4+751|fivesuperior=5+751|sixsuperior=6+751|sevensuperior=7+751|eightsuperior=8+751|ninesuperior=9+751]


hb-shape Roboto\[ital\,wdth\,wght\].ttf --features subs 0123456789
[zerosub=0+751|oneinferior=1+751|twosub=2+751|threesub=3+751|foursub=4+751|fivesub=5+751|sixinferior=6+751|sevensub=7+751|eightsub=8+751|nineinferior=9+751]
```

Test have also been added to ensure these features exist in future releases.

**Comment by kpozin** [comment]
Looks great. Thank you!

**Comment by davelab6** [comment]
Thanks all

**Review by davelab6 — APPROVED** [review]

**Comment by m4rc1e** [comment]
v3.005 which includes this fix has been cut https://github.com/googlefonts/roboto-classic/releases/tag/v3.005

**Pull request merged**
